### ISSUE TITLE
Needs work

### ISSUE THREAD

**Issue by axeberg** [chas-academy/07-recipe-app-backend-peterheinum#1]
Seems like you are on your way to finishing this. 

- [  ~ ]  Kunna registrera konto i API:et
    - [ ~ ]  Använd JWT baserade tokens för kommunikation
- [X]  Spara skapade receptlistor
- [ ~ ]  CRUD på listor
    - [ ]  Samtliga listor måste vara knutna till en användare och får bara ändras/läsas av samma användare

**Comment by peterheinum** [comment]
Yes problem is that my backend isn't online. Everything works on my machine :)

**Comment by axeberg** [comment]
Progress @peterheinum ?

**Comment by peterheinum** [comment]
Nää har inte försök nått mer. Men jag tror borde kolla nån tutorial på laravel uploading. 

För övrigt, var det tänkt att man skulle ha LISTOR med recept eller bara recept och sen visas de recept man sparat för användaren som sparat dem?

**Comment by axeberg** [comment]
Listor med recept.

CRUD på listor
